image:
  repository: kodelib/code-server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

sidecar:
  image:
    repository: "kodelib/code-server-sidecar"
    pullPolicy: IfNotPresent
    tag: "0.1.0"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass:

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

app:
  base_path: /
  env: {}
  args: 
    - --host=0.0.0.0
    - --disable-telemetry