version: "1.0"

variables:
  NAME: code-server

jobs:
  install:
    commands:
      - kubectx minikube
      - >
        helm upgrade "${NAME}" "${PWD}"
        --install 
        --set persistence.enabled="true"
        --set persistence.size="1Gi"

  test:
    commands:
      - kubectx minikube
      - helm test "${NAME}"

  uninstall:
    commands:
      - kubectx minikube
      - helm uninstall "${NAME}"
