version: "1.0"

variables:
  NAME: code-server

jobs:
  install:
    commands:
      - kubectx minikube
      - >
        helm upgrade "${NAME}" "${PWD}"
        --install
        --set image.pullPolicy=Always
        --set persistence.enabled="true"
        --set persistence.size="1Gi"
        --set env.PASSWORD=1234567890

  test:
    commands:
      - kubectx minikube
      - helm test "${NAME}"

  uninstall:
    commands:
      - kubectx minikube
      - helm uninstall "${NAME}"
